/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Chaitanya Krishnan (https://sketchfab.com/chaitanyak)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hologram-zLEvLIv5tDvposM5dPqrg50wK51
title: hologram
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/hologram.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={0.3} rotation={[0, 0, 0]} position={[0.4, -0.8, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        {/* <group position={[7.33, 0.03, -0.21]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[1, 1, 0.72]}>
          <mesh geometry={nodes.Sphere006_0.geometry} material={materials.grid} />
          <mesh geometry={nodes.Sphere006_0_1.geometry} material={materials.grid} />
          <mesh geometry={nodes.Sphere006_0_2.geometry} material={materials.grid} />
          <mesh geometry={nodes.Sphere006_0_3.geometry} material={materials.grid} />
          <mesh geometry={nodes.Sphere006_0_4.geometry} material={materials.grid} />
        </group> */}
        <group position={[-1.03, -0.19, -8.89]} scale={[5.26, 5.26, 0.75]}>
          <mesh geometry={nodes.Cylinder042_0.geometry} material={materials.ring} />
          <mesh geometry={nodes.Cylinder042_1.geometry} material={materials.perimeter} />
          <mesh geometry={nodes.Cylinder042_2.geometry} material={materials.inner_ring} />
          <mesh geometry={nodes.Cylinder042_3.geometry} material={materials.base} />
        </group>
        <group position={[-1.03, -0.19, -8.16]} scale={[3.82, 3.82, 0.11]}>
          <mesh geometry={nodes.Cylinder043_0.geometry} material={materials.emitter} />
        </group>
        <group position={[-1.11, 0.05, -5.24]} rotation={[-Math.PI, 0, 0]} scale={4.28}>
          <mesh geometry={nodes.Cone_0.geometry} material={materials.rays} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/hologram.gltf')
